# FROM apache/spark:3.5.1

# USER root
# RUN pip install --no-cache-dir boto3 pandas

# COPY jobs/ /opt/spark/jobs/

FROM apache/spark:3.5.1

USER root

# Pre-download S3A JARs so jobs don't need runtime Maven resolution
RUN curl -fL -o /opt/spark/jars/hadoop-aws-3.3.4.jar \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar && \
    curl -fL -o /opt/spark/jars/aws-java-sdk-bundle-1.12.262.jar \
    https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY jobs/ /opt/spark/jobs/