FROM python:3.11-slim

WORKDIR /app

COPY producer2/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY producer2/producer2.py .
COPY contracts ./contracts

CMD ["python", "producer2.py"]